<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Onderzoeksontwerp en Beschrijvende Statistiek - 7&nbsp; Numerieke variabelen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./practica.html" rel="next">
<link href="./factoren.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalk in" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./numeriek.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Numerieke variabelen</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalk in" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Onderzoeksontwerp en Beschrijvende Statistiek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welkom</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inleiding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R en RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bewerken.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Bewerken</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grafieken.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Grafieken maken</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factoren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorische variabelen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numeriek.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Numerieke variabelen</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./practica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practica</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_practica/practicum1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practicum 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_practica/practicum2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practicum 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_practica/practicum3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practicum 3</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul class="collapse">
  <li><a href="#de-data-in-dit-hoofdstuk" id="toc-de-data-in-dit-hoofdstuk" class="nav-link active" data-scroll-target="#de-data-in-dit-hoofdstuk">De data in dit hoofdstuk</a></li>
  <li><a href="#distributies-zichtbaar-maken" id="toc-distributies-zichtbaar-maken" class="nav-link" data-scroll-target="#distributies-zichtbaar-maken"><span class="header-section-number">7.1</span> Distributies zichtbaar maken</a></li>
  <li><a href="#beschrijvende-statistieken-berekenen" id="toc-beschrijvende-statistieken-berekenen" class="nav-link" data-scroll-target="#beschrijvende-statistieken-berekenen"><span class="header-section-number">7.2</span> Beschrijvende statistieken berekenen</a></li>
  <li><a href="#centrummaten-zichtbaar-maken" id="toc-centrummaten-zichtbaar-maken" class="nav-link" data-scroll-target="#centrummaten-zichtbaar-maken"><span class="header-section-number">7.3</span> Centrummaten zichtbaar maken</a></li>
  <li><a href="#de-data-zichtbaar-maken" id="toc-de-data-zichtbaar-maken" class="nav-link" data-scroll-target="#de-data-zichtbaar-maken"><span class="header-section-number">7.4</span> De data zichtbaar maken</a></li>
  <li><a href="#verder-leren" id="toc-verder-leren" class="nav-link" data-scroll-target="#verder-leren">Verder leren</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-Numeriek" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Numerieke variabelen</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Numerieke variabelen bieden meer mogelijkheden voor beschrijvende statistieken dan de categorische variabelen uit het vorige hoofdstuk. In dit hoofdstuk gaan we zien hoe je distributies (verdelingen) van numerieke variabelen zichtbaar kunt maken, hoe je centrum- en spreidingsmaten kunt berekenen en hoe je in een grafiek zowel een algemeen beeld (centrummaat) als de data zelf (spreiding) kunt laten zien.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Na afloop van dit hoofdstuk:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>kun je numerieke variabelen visualiseren met verschillende soorten plots (histogram, density, dot, box) in <code>ggplot2</code>;</li>
<li>kun je meerdere <em>geoms</em> combineren om zowel de data zelf als patronen in de data zichtbaar te maken;</li>
<li>kun je beschrijvende statistieken berekene met <code>tidyverse</code>;</li>
<li>kun je datatabellen omzetten van <em>wide</em> naar <em>long</em> formaat.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
codeboek
</div>
</div>
<div class="callout-body-container callout-body">
<p>In deze cursus leer je werken met zo’n 100 veelgebruikte functies in <code>R</code>. Het is belangrijk om voor jezelf een goed overzicht te houden van deze functies. Werk hier actief aan door een eigen codeboek aan te maken. Voeg tijdens of na afloop van het bestuderen van dit hoofdstuk de codes toe aan jouw codeboek.</p>
</div>
</div>
<section id="de-data-in-dit-hoofdstuk" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="de-data-in-dit-hoofdstuk">De data in dit hoofdstuk</h2>
<p>We gebruiken in dit hoofdstuk de data van Nederlandse kinderen uit Workbank. We kijken naar de woordenschat bij iets oudere kinderen (ca. 1.5 tot 2.5 jaar). De data zijn te vinden in het bestand <code>wordbank_dutch_WS_child.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_datasets/wordbank_dutch_WS_child.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(wordbank_dutch_child)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 303
Columns: 22
$ downloaded           &lt;date&gt; 2025-07-16, 2025-07-16, 2025-07-16, 2025-07-16, …
$ language             &lt;chr&gt; "Dutch", "Dutch", "Dutch", "Dutch", "Dutch", "Dut…
$ form                 &lt;chr&gt; "WS", "WS", "WS", "WS", "WS", "WS", "WS", "WS", "…
$ dataset_name         &lt;chr&gt; "Bergman", "Bergman", "Bergman", "Bergman", "Berg…
$ child_id             &lt;dbl&gt; 76526, 76527, 76528, 76529, 76530, 76531, 76532, …
$ age                  &lt;dbl&gt; 18, 18, 19, 18, 18, 18, 18, 18, 18, 18, 17, 17, 1…
$ comprehension        &lt;dbl&gt; 162, 405, 381, 313, 278, 90, 266, 324, 394, 154, …
$ production           &lt;dbl&gt; 37, 28, 107, 122, 95, 11, 35, 6, 134, 17, 41, 25,…
$ is_norming           &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …
$ birth_order          &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ caregiver_education  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ethnicity            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ race                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ sex                  &lt;chr&gt; "Female", "Female", "Female", "Female", "Female",…
$ birth_weight         &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ born_early_or_late   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ gestational_age      &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ zygosity             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ language_exposures   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ health_conditions    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ monolingual          &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…
$ typically_developing &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…</code></pre>
</div>
</div>
<p>We hebben 303 observaties en wederom 22 variabelen. We gaan de dataset inperken naar 4 variabelen en zetten de variabele <code>child_id</code> om in een factor. De overige drie variabelen <code>age</code> (leeftijd in maanden), <code>comprehension</code> (hoeveel woorden van de vragenlijst een kind begrijpt) en <code>production</code> (hoeveel woorden van de vragenlijst een kind zelf al gebruikt) zijn al numeriek.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="ot">&lt;-</span> wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(child_id, age, comprehension, production) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">child_id =</span> <span class="fu">as.factor</span>(child_id))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distributies-zichtbaar-maken" class="level2 page-columns page-full" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="distributies-zichtbaar-maken"><span class="header-section-number">7.1</span> Distributies zichtbaar maken</h2>
<p>We gaan de variabele <code>age</code> verder bekijken. Wat is de verdeling van leeftijden in onze dataset? We kunnen met <code>count()</code> tellen hoe vaak elke leeftijd voorkomt. We gebruiken hier het commando <code>print(n=20)</code> om meer rijen zichtbaar te maken dan de standaard 10 rijen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(age) <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">20</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 2
     age     n
   &lt;dbl&gt; &lt;int&gt;
 1    16     4
 2    17    49
 3    18    68
 4    19     7
 5    20     7
 6    21     7
 7    22     7
 8    23    51
 9    24    31
10    25     6
11    26     6
12    27     5
13    28     6
14    29    23
15    30    24
16    31     2</code></pre>
</div>
</div>
<p>Voor elke unieke waarde van de variabele <code>age</code> krijgen we hier te zien hoe vaak deze voorkomt in de dataset.</p>
<p>Dit is in feite ook wat een histogram voor ons doet: het telt het aantal voorkomens waarbij het de numerieke variabele opdeelt in een aantal groepen. Die groepen worden <em>bins</em> genoemd. Elke staaf in het histogram beeldt een bin uit. Het standaard aantal bins voor <code>geom_histogram()</code> is 30 en dat levert niet altijd het beste resultaat, zoals <code>R</code> zelf ook aangeeft met de boodschap ‘Pick better value with `binwidth’’. Als we goed kijken naar de data in <a href="#fig-num-hist">Figuur&nbsp;<span>7.1</span></a> dan zien we dat de staven de data op een vreemde manier indelen en ieder geval niet per maand. Dit zien we bijvoorbeeld als we kijken naar de hele getallen op de x-as. Soms staat het bijbehorende streepje midden in een staaf (bij 16), soms aan het begin (bij 20) en soms aan het eind (bij 24 en 28).</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display page-columns page-full">
<div id="fig-num-hist" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="numeriek_files/figure-html/fig-num-hist-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figuur&nbsp;7.1: Histogram met door <code>R</code> zelf gekozen aantal bins</figcaption>
</figure>
</div>
</div>
</div>
<p>Het is dus bij een histogram belangrijk om zelf te bedenken hoe je de data wilt opdelen. Met het argument <code>bins =</code> binnen <code>geom_histogram()</code> kun je aangeven in hoeveel staven je het histogram wilt opdelen. Omdat we bij het tellen hebben gezien dat er 16 verschillende leeftijden voorkomen, ligt het voor deze dataset voor de hand om een getal te nemen waar je 16 door kunt delen om een geheel getal te krijgen. We kiezen hier dus 16. Elke maand krijgt dan zijn eigen staaf.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De staven zien we alleen nog niet zo duidelijk, omdat zowel de <code>fill</code> als de <code>color</code> standaard op zwart staan ingesteld. We geven de randen van de staaf de kleur <code>white</code> zodat we de bins kunnen zien en geven de staven ook meteen een kleur:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">16</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In plaats van het argument <code>bins</code> kun je ook <code>binwidth</code> gebruiken, zoals <code>R</code> zelf al suggereerde. Met <code>binwidth</code> specificeer je de de stappen waarin je wilt tellen. Aangezien we hier te maken hebben met gehele getallen kiezen we voor 1, maar je zou bijvoorbeeld ook per 2 of 3 maanden kunnen tellen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Dit histogram geeft met logische bins een goed beeld van de verdeling van de data. We zien dat een aantal leeftijden veel meer voorkomt in de data dan andere. Door de plaatsing van de getallen op de x-as is het alleen niet meteen duidelijk om welke leeftijden het gaat. Sommige streepjes staan midden in een staaf (bijv. 20 en 25), andere staan tussen staven in (bijv. 17.5). De nummering op de x-as passen we aan met <code>scale_x_continuous()</code> (voor de y-as is er <code>scale_y_continuous</code> en er zijn ook varianten voor discrete assen). Het argument <code>breaks</code> specificeert waar we getallen willen. Dit kun je volledig handmatig doen door een vector van getallen te specificeren met <code>c()</code>. Om typewerk te besparen doen we het hier met <code>seq()</code> waarbij we aangeven dat we de labels bij 16 willen laten beginnen en laten doorlopen tot en met 32 in stapjes van 2 (dus 16, 18, 20, …).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">16</span>, <span class="dv">32</span>, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Het blijft bij histogrammen opletten waar elke staaf voor staat. We hebben de getallen nu midden in de staaf staan, maar vaak zie je het ook links of juist rechts van de staaf.</p>
<section id="density" class="level3 page-columns page-full" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="density"><span class="header-section-number">7.1.1</span> Density</h3>
<p>In plaats van een histogram kunnen we de verdeling ook zichtbaar maken met een <em>density plot</em>. We hoeven hiervoor alleen een ander geom te specificeren. We gebruiken <code>geom_density()</code> en we geven aan dat we de lijn en opvulling van de grafiek in dezelfde kleur willen, met <code>alpha = .5</code> geven we aan dat we de opvulling enigszins transparant willen maken.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"thistle3"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hetzelfde kunnen we doen voor de variabele <code>comprehension</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> comprehension)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"bisque3"</span>, <span class="at">fill =</span> <span class="st">"bisque3"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De reden dat we de opvulling transparant maken is dat we dat mooier vinden, maar vooral ook dat het mogelijk maakt om meerdere variabelen in een grafiek zichtbaar te maken. We kunnen bijvoorbeeld proberen <code>production</code> toe te voegen om zo de verdelingen te vergelijken.</p>
<p>De manier waarop onze dataset is vormgeven met een aparte kolom voor <code>comprehension</code> en een voor <code>production</code> maakt dit wel wat uitdagender. Aangezien we in <code>ggplot()</code> de variabele <code>comprehension</code> al op x hebben afgebeeld, kunnen we daar <code>production</code> niet meer toevoegen. De enige optie die we hebben is om gebruik te maken van het feit dat we binnen het geom een nieuwe mapping kunnen maken in de <code>aes()</code> van het geom. We voegen dus een nieuw <code>geom_density()</code> toe met een eigen kleur. Omdat dit geom later wordt toegevoegd, wordt het over het eerdere heen getekend. De transparantiewaarde met <code>alpha</code> komt hier dus goed van pas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> comprehension)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"bisque3"</span>, <span class="at">fill =</span> <span class="st">"bisque3"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> production), <span class="at">color =</span> <span class="st">"deepskyblue4"</span>, <span class="at">fill =</span> <span class="st">"deepskyblue4"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Deze grafiek laat de densities van beiden variabelen zien, maar heeft zijn problemen. De x-as zegt nog steeds ‘comprehension’ en het wordt niet duidelijk welke kleur bij welke variabele hoort. Het aanpassen van het label van de x-as via <code>labs()</code> gaat dit niet volledig oplossen.</p>
<p>We kunnen proberen om de mapping van <code>comprehension</code> naar de x-as te verschuiven van <code>ggplot()</code> naar de <code>aes()</code> van de eerste aanroep van `geom_density()’, maar ook dit verandert niets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> comprehension), <span class="at">color =</span> <span class="st">"bisque3"</span>, <span class="at">fill =</span> <span class="st">"bisque3"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> production), <span class="at">color =</span> <span class="st">"deepskyblue4"</span>, <span class="at">fill =</span> <span class="st">"deepskyblue4"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Het probleem zit dieper. Wanneer we de kleur willen laten variëren op basis van een variabele, dan moeten de waardes van die variabele in dezelfde kolom staan. Dat is hier niet het geval. We hebben per kind een aparte kolom voor <code>comprehension</code> en een voor <code>production</code>. Het zijn twee aparte variabelen. De dataset staat in wat we noemen <em>wide format</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 303 × 4
  child_id   age comprehension production
  &lt;fct&gt;    &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
1 76526       18           162         37
2 76527       18           405         28
# ℹ 301 more rows</code></pre>
</div>
</div>
<p>Dit formaat is handig als we de variabelen apart willen laten zien, maar niet als we ze eigenlijk als waardes van één variabele willen behandelen. We moeten dan dus een kolom aanmaken waarin we per kind twee rijen krijgen, een met de waarde voor <code>comprehension</code> en een voor <code>production</code>. Dit noemen we <em>long format</em>. We gaan hiervoor een nieuwe variabele aanmaken die we <code>skill</code> noemen. Dit doen we met de functie <code>pivot_longer()</code> (zoals je misschien al had geraden is er ook de tegenhanger <code>pivot_wider()</code>). In het argument <code>cols</code> geven we aan welke variabelen we willen samenvoegen tot een nieuwe variabele (de kolomnamen worden de namen van de levels). Met <code>names_to</code> geven we de naam van de nieuwe variabele aan en met <code>values_to</code> geven we aan in welke variabele de waarden de oorspronkelijke variabelen terecht gaan komen. Het eerste kind (met id 76526) scoorde 162 op <code>comprehension</code> en 37 op <code>production</code>. Deze waardes zullen op twee rijen komen in de nieuwe variabele <code>number_of_words</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="ot">&lt;-</span> wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(comprehension, production), </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"skill"</span>, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"number_of_words"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 606 × 4
  child_id   age skill         number_of_words
  &lt;fct&gt;    &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;
1 76526       18 comprehension             162
2 76526       18 production                 37
3 76527       18 comprehension             405
4 76527       18 production                 28
# ℹ 602 more rows</code></pre>
</div>
</div>
<p>We zien nu dat ieder kind twee rijen in de dataset heeft. De lengte van de dataset is dan ook verdubbeld van 303 naar 606. In de eerste twee rijen zien we de scores van 162 en 37 voor kind met id 76526 terug en die zijn in de kolom <code>skill</code> gelabelled als <code>comprehension</code> en <code>production</code>. We zetten de nieuwe variabele <code>skill</code> nog even om naar een factor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="ot">&lt;-</span> dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">skill =</span> <span class="fu">as.factor</span>(skill))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nu kunnen we de grafiek maken zoals we hem wilden hebben (<a href="#fig-num-density">Figuur&nbsp;<span>7.2</span></a>), waarbij we de nieuwe variabele <code>skill</code> afbeelden op de kleur en fill van de density plots. We krijgen hiermee meteen een legenda die aangeeft welke skill bij welke kleur hoort. We hebben nu ook maar één aanroep van <code>geom_density()</code> nodig.</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color =</span> skill, <span class="at">fill =</span> skill), <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-num-density" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="numeriek_files/figure-html/fig-num-density-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figuur&nbsp;7.2: Overlappende density plot op basis van data in <em>long format</em></figcaption>
</figure>
</div>
</div>
</div>
<p>De grafiek laat nu duidelijk zien dat er een verschil in verdeling is tussen begrip en productie. Kinderen kennen meer woorden dan ze gebruiken.</p>
<p>Als we geen overlap willen van de density plots, maar ze wel in één figuur willen laten zien kunnen we nu ook <code>facet_wrap()</code> gebruiken waarbij we de grafiek splitsen op <code>skill</code>. We krijgen dan een aparte grafiek voor <code>comprehension</code> en <code>production</code>. Omdat deze levels al benoemd zijn in de titels van de aparte plots, is de legenda overbodig. We halen de legenda weg met <code>show.legend = F</code> (waarbij <code>F</code> een afkorting is voor <code>FALSE</code>). De alpha-waarde verhogen we weer iets, aangezien de densities niet meer overlappen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color =</span> skill, <span class="at">fill =</span> skill), <span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> skill) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We gebruiken deze grafiek om nog wat extra opties te laten zien om het uiterlijk van grafieken naar je hand te zetten. We gaan hier de titel van de facet wat duidelijker maken door het lettertype te vergroten en dik te drukken. Deze aanpassing doen we weer binnen <code>theme()</code>. Met <code>strip.text</code> kunnen we de titel aanpassen. We verhogen de grootte naar 18 en zetten de titel in <strong>bold</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color =</span> skill, <span class="at">fill =</span> skill), <span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> skill) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Facets kunnen handig zijn om inzicht te krijgen in hoe een variabele zich gedraagt op niveaus van een andere variabele. Aangezien <code>age</code> een discrete numerieke variabele is, kunnen we per maand een aparte density plot maken. Bij continue variabelen is dat lastiger, aangezien het dan minder duidelijk is waar je de grenzen moet leggen. We kiezen ervoor om de woordproductie per maand te laten zien. Aangezien we nu in <em>long format</em> zitten betekent dat we de data moeten filteren op <code>skill</code>. Zo zie je dat het ene formaat handig kan zijn voor de ene soort visualisatie en het andere voor een andere. Het is dus handig als je makkelijk kunt switchen tussen formaten met de <code>pivot_</code>-functies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(skill <span class="sc">==</span> <span class="st">"production"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"deepskyblue4"</span>, <span class="at">fill =</span> <span class="st">"deepskyblue4"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> age) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Distribution by age"</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We zien in de figuur een duidelijke ontwikkeling. Aan het begin en het eind zijn er duidelijk pieken en zitten de kinderen allemaal in hetzelfde gebied. Tussen de 20 en 27 maanden is er meer variatie. Sommige kinderen produceren al veel woorden terwijl anderen nog wat lagere aantallen laten zien.</p>
</section>
<section id="boxplots" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="boxplots"><span class="header-section-number">7.1.2</span> boxplots</h3>
<p>Een derde optie om verdelingen zichtbaar te maken zijn boxplots. We zetten onze eerdere density plot <a href="#fig-num-density">Figuur&nbsp;<span>7.2</span></a> om in een boxplot door <code>geom_density()</code> te vervangen door <code>geom_boxplot()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words, <span class="at">color =</span> skill, <span class="at">fill =</span> skill)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Net zoals het histogram komt het boxplot met een aantal eigenaardigheden. Zo zien we in bovenstaande figuur getallen staan op de y-as. Het lijkt erop dat de levels van de variabele <code>skill</code> ieder een waarde hebben gekregen (rond 0.2 en -0.2). Die getallen willen we weghalen, aangezien ze betekenisloos zijn. De oplossing daarvoor is simpel. We voegen <code>y = skill</code> toe aan de <code>aes()</code>-mapping (hier in <code>ggplot()</code>). Om te zorgen dat de grafiek niet redundant wordt, halen we meteen de legenda weg.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_words, <span class="at">y =</span> skill, <span class="at">color =</span> skill, <span class="at">fill =</span> skill)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> .<span class="dv">4</span>, <span class="at">alpha =</span> .<span class="dv">3</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"number of words"</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Het toevoegen van een y-variabele helpt ons ook als we maar één variabele willen afbeelden in de boxplot. Wanneer we dit niet doen krijgen we weer getallen op de y-as.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(skill <span class="sc">==</span> <span class="st">"production"</span>) <span class="sc">%&gt;%</span> <span class="co">#ontdubbelen van de data, elk kind staat er nu 2 keer in</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"thistle3"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>, <span class="at">width =</span> .<span class="dv">4</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Met een omweg kunnen we van deze getallen afkomen. We voegen een <em>dummy</em>-variabele toe op y met <code>y = factor(0)</code> en we specificeren vervolgens in <code>theme()</code> met <code>element_blank()</code> dat we geen tekst op de y-as willen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(skill <span class="sc">==</span> <span class="st">"production"</span>) <span class="sc">%&gt;%</span> <span class="co">#ontdubbelen van de data, elk kind staat er nu 2 keer in</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> <span class="fu">factor</span>(<span class="dv">0</span>))) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"thistle3"</span>, <span class="at">fill =</span> <span class="st">"thistle3"</span>, <span class="at">width =</span> .<span class="dv">4</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hiermee wordt de box in boxplot ook minder breed, in overeenstemming met de door ons gevraagde breedte met het argument <code>width</code>.</p>
<p>Boxplots zijn ideaal om <em>outliers</em> zichtbaar te maken. Dit zijn punten die meer dan <span class="math inline">\(1.5 \times IQR\)</span> onder het eerste kwartiel of boven het derde kwartiel liggen. In de variabelen in onze dataset zitten geen outliers. Voor de oefening voegen we daarom twee outliers toe. We maken hiervoor eerst een datatabel aan met verzonnen data van twee kinderen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>outlier_cases <span class="ot">&lt;-</span> <span class="fu">tribble</span>(<span class="sc">~</span>child_id, <span class="sc">~</span>age, <span class="sc">~</span>skill, <span class="sc">~</span>number_of_words,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                   <span class="dv">99999</span>, <span class="dv">38</span>, <span class="st">"production"</span>, <span class="dv">999</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                   <span class="dv">99999</span>, <span class="dv">42</span>, <span class="st">"production"</span>, <span class="dv">999</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>outlier_cases <span class="ot">&lt;-</span> outlier_cases <span class="sc">%&gt;%</span> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">child_id =</span> <span class="fu">as.factor</span>(child_id))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Met <code>add_case()</code> voegen we deze twee observaties toe aan onze datatabel. In <code>geom_boxplot()</code> specificeren we met <code>outlier.color</code> en <code>outlier.alpha</code> de kleur en transparantie van de punten waarmee de outliers worden getoond.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(skill <span class="sc">==</span> <span class="st">"production"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_case</span>(outlier_cases) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> <span class="fu">factor</span>(<span class="dv">0</span>))) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"thistle3"</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">"thistle3"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">width =</span> .<span class="dv">4</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">"red"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="beschrijvende-statistieken-berekenen" class="level2 page-columns page-full" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="beschrijvende-statistieken-berekenen"><span class="header-section-number">7.2</span> Beschrijvende statistieken berekenen</h2>
<p><code>R</code> bieden verschillende functies waarmee we beschrijvende statistieken kunnen berekenen. <a href="#tbl-num-functies">Tabel&nbsp;<span>7.1</span></a> geeft een overzicht van veelgebruikte functies.</p>
<div id="tbl-num-functies" class="anchored page-columns page-full">
<table class="table">

<colgroup>
<col style="width: 16%">
<col style="width: 41%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>functienaam</th>
<th>werking</th>
<th>werkt met <code>summarize()</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>range()</code></td>
<td>bepaalt het bereik van een variabele (geeft minimale en maximale waarde)</td>
<td>nee</td>
</tr>
<tr class="even">
<td><code>min()</code></td>
<td>bepaalt de minimale waarde van een variabele</td>
<td>ja</td>
</tr>
<tr class="odd">
<td><code>max()</code></td>
<td>bepaalt de maximale waarde van een variabele</td>
<td>ja</td>
</tr>
<tr class="even">
<td><code>mean()</code></td>
<td>berekent het gemiddelde van een variabele</td>
<td>ja</td>
</tr>
<tr class="odd">
<td><code>median()</code></td>
<td>berekent de mediaan van een variabele</td>
<td>ja</td>
</tr>
<tr class="even">
<td><code>sd()</code></td>
<td>berekent de standaarddeviatie van een variabele</td>
<td>ja</td>
</tr>
<tr class="odd">
<td><code>var()</code></td>
<td>berekent de variantie van een variabele</td>
<td>ja</td>
</tr>
<tr class="even">
<td><code>IQR()</code></td>
<td>bepaalt de interkwartielafstand (IQR) van een variabele</td>
<td>ja</td>
</tr>
<tr class="odd">
<td><code>quantile()</code></td>
<td>bepaalt de kwantielen van een variabele, hiervoor moet je met het argument <code>probs =</code> aangeven welke kwantielen je wilt</td>
<td>nee (alleen wanneer er maar één kwantiel wordt opgevraagd)</td>
</tr>
<tr class="even">
<td><code>summary()</code></td>
<td>geeft een aantal beschrijvende statistieken van een variabele (min, max, 1e en 3e kwartiel, mediaan, gemiddelde)</td>
<td>nee</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Tabel&nbsp;7.1: Overzicht van functies waarmee beschrijvende statistieken kunnen worden berekend</div></div>
<p>De meeste van deze functies kunnen gecombineerd worden met <code>summarize()</code> (of <code>summarise()</code>), de <code>Tidyverse</code>-functie die je moet gebruiken om beschrijvende statistieken te berekenen. De functies die hier niet mee combineren kun je gebruiken met de <code>$</code>-notatie om er een variabele uit te lichten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wordbank_dutch_child<span class="sc">$</span>age)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  16.00   18.00   23.00   22.01   24.00   31.00 </code></pre>
</div>
</div>
<p>Een alternatief hiervoor is de functie <code>with()</code> waarin je de naam van de datatabel waarin de variabele zit meegeeft:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(wordbank_dutch_child,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">quantile</span>(age, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, .<span class="dv">25</span>, .<span class="dv">50</span>, .<span class="dv">75</span>, <span class="dv">1</span>)))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
  16   18   23   24   31 </code></pre>
</div>
</div>
<p>Met <code>summarize()</code> kun je meerdere beschrijvende statistieken tegelijk laten berekenen. Je kunt hierbij zelf een naam geven aan de te berekenen maat. Deze naam komt voor het <code>=</code>-teken.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_age =</span> <span class="fu">sd</span>(age),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_comprehension =</span> <span class="fu">mean</span>(comprehension),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_comprehension =</span> <span class="fu">median</span>(comprehension))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  mean_age sd_age mean_comprehension median_comprehension
     &lt;dbl&gt;  &lt;dbl&gt;              &lt;dbl&gt;                &lt;dbl&gt;
1     22.0   4.47               412.                  402</code></pre>
</div>
</div>
<p>De functie <code>summarize()</code> kun je combineren met <code>group_by()</code> om beschrijvende statistieken per level van een (andere) variabele te berekenen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age) <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_comprehension =</span> <span class="fu">mean</span>(comprehension),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_production =</span> <span class="fu">mean</span>(production)) <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 3
    age mean_comprehension mean_production
  &lt;dbl&gt;              &lt;dbl&gt;           &lt;dbl&gt;
1    16               125.            32.5
2    17               243.            50.5
3    18               282.            65.2
4    19               257.            83  
# ℹ 12 more rows</code></pre>
</div>
</div>
<p>In <em>long format</em> kunnen we <code>group_by</code> ook gebruiken om beschrijvende statistieken voor combinaties van variabelen te berekenen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age, skill) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_number_words =</span> <span class="fu">mean</span>(number_of_words)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'age'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 3
# Groups:   age [16]
    age skill         mean_number_words
  &lt;dbl&gt; &lt;fct&gt;                     &lt;dbl&gt;
1    16 comprehension             125. 
2    16 production                 32.5
3    17 comprehension             243. 
4    17 production                 50.5
# ℹ 28 more rows</code></pre>
</div>
</div>
<p>Het package <code>skimr</code> biedt een functie <code>skim()</code> die je in een keer een overzicht geeft van allerlei statistieken, waaronder ook aantal observaties en missing data, gesorteerd voor categorische en numerieke variabele apart. Hiervoor moet je het package <code>skimr</code> natuurlijk wel geïnstalleerd hebben en aanroepen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>wordbank_dutch_child <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<table class="table table-sm table-striped small">

<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Data summary</div><p><strong>Variable type: factor</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">child_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">210</td>
<td style="text-align: left;">766: 3, 766: 3, 766: 3, 766: 3</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22.01</td>
<td style="text-align: right;">4.47</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">18.0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">24.0</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">▇▁▆▁▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">comprehension</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">412.39</td>
<td style="text-align: right;">188.30</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">266.0</td>
<td style="text-align: right;">402</td>
<td style="text-align: right;">588.5</td>
<td style="text-align: right;">703</td>
<td style="text-align: left;">▃▆▆▅▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">production</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">237.49</td>
<td style="text-align: right;">219.71</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">44.5</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">431.5</td>
<td style="text-align: right;">696</td>
<td style="text-align: left;">▇▂▂▂▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>De functie produceert zelfs een klein histogram om de verdeling van numerieke variabelen weer te geven. Door de naam van een variabele in te vullen in <code>skim()</code> krijg je alleen het overzicht voor die variabele. Ook deze functie kun je gebruiken in combinatie met <code>group_by()</code>:</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>dutch_child_long <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(skill) <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>(number_of_words)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<table class="table table-sm table-striped small">

<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">606</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">skill</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Data summary</div><p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: left;">skill</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">number_of_words</td>
<td style="text-align: left;">comprehension</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">412.39</td>
<td style="text-align: right;">188.30</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">266.0</td>
<td style="text-align: right;">402</td>
<td style="text-align: right;">588.5</td>
<td style="text-align: right;">703</td>
<td style="text-align: left;">▃▆▆▅▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">number_of_words</td>
<td style="text-align: left;">production</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">237.49</td>
<td style="text-align: right;">219.71</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">44.5</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">431.5</td>
<td style="text-align: right;">696</td>
<td style="text-align: left;">▇▂▂▂▂</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="centrummaten-zichtbaar-maken" class="level2 page-columns page-full" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="centrummaten-zichtbaar-maken"><span class="header-section-number">7.3</span> Centrummaten zichtbaar maken</h2>
<p>Berekende beschrijvende statistieken van numerieke variabelen kunnen we zichtbaar maken met <code>ggplot</code>. We gebruiken hiervoor <code>geom_point()</code> i.p.v. een staafdiagram. Dit omdat we later ook de ruwe datapunten zichtbaar willen maken. We berekenen als voorbeeld eerst het gemiddelde aantal begrepen en geproduceerde woorden per leeftijd:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>dutch_means <span class="ot">&lt;-</span> dutch_child_long <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age, skill) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_number_words =</span> <span class="fu">mean</span>(number_of_words))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'age'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>dutch_means</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 3
# Groups:   age [16]
     age skill         mean_number_words
   &lt;dbl&gt; &lt;fct&gt;                     &lt;dbl&gt;
 1    16 comprehension             125. 
 2    16 production                 32.5
 3    17 comprehension             243. 
 4    17 production                 50.5
 5    18 comprehension             282. 
 6    18 production                 65.2
 7    19 comprehension             257. 
 8    19 production                 83  
 9    20 comprehension             414. 
10    20 production                188. 
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>Vervolgens plotten we deze met behulp van <code>geom_point()</code> waarbij we de twee typen skills weer hun eigen kleur geven.</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>dutch_means <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> mean_number_words, <span class="at">color =</span> skill)) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> .<span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"mean number of words"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"age in months"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Word comprehension and production by age"</span>) <span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"bisque3"</span>, <span class="st">"deepskyblue4"</span>)) <span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">14</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-num-skills" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="numeriek_files/figure-html/fig-num-skills-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figuur&nbsp;7.3: Gemiddelde begrip en productie van woorden in een dotplot.</figcaption>
</figure>
</div>
</div>
</div>
<p>Bovenstaande grafiek is niet (of moeilijk) te maken met <em>wide format</em>, aangezien we een variabele (<code>skill</code>) willen afbeelden op de kleur van de punten. Het <em>wide format</em> is wel geschikt om ruwe data te plotten. Die gaan we nu toevoegen.</p>
</section>
<section id="de-data-zichtbaar-maken" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="de-data-zichtbaar-maken"><span class="header-section-number">7.4</span> De data zichtbaar maken</h2>
<p>Centrummaten geven maar een erg beperkt beeld van de data. We willen daarom naast de centrummaat (hier het gemiddelde) ook iets van de spreiding in de data laten zien. We doen dat door van elk kind de geobserveerde waarde te plotten. Op basis van deze geobserveerde waardes hebben we het gemiddelde per leeftijd berekend.</p>
<p>We gebruiken als basis de code voor <a href="#fig-num-skills">Figuur&nbsp;<span>7.3</span></a>. Om de grafiek overzichtelijk te houden voegen we alleen de datapunten voor <code>production</code> toe. We voegen aan deze grafiek de observaties per kind toe via een tweede aanroep van <code>geom_point()</code> (regel 4 in onderstaand codeblok) waarbij we de waardes uit een andere datatabel (<code>wordbank_dutch_child</code>) halen dan waar we de gemiddelden uit halen (<code>dutch_means</code>, zie r. 1). De volgorde van de twee aanroepen van <code>geom_point()</code> is hier belangrijk. Om de gemiddelden over de individuele punten heen te plotten, gebruiken we de eerste aanroep van <code>geom_point()</code> voor de individuele punten en de tweede aanroep voor de gemiddelden. We voegen aan het tweede geom expliciet de dataset toe met het argument <code>data =</code> (anders zou de dataset van <code>ggplot()</code> worden overgenomen) en we maken ook een nieuwe <code>aes()</code> aan (regel 4) om de juiste variabelen uit de dataset zichtbaar te maken. De individuele punten willen we zichtbaar houden en daarom zetten we <code>alpha</code> wat lager en om de punten te onderscheiden van de punten die het gemiddelde weergeven maken we de observaties van individuele kinderen grijs. We lichten de betekenis van de twee typen punten toe door een <code>caption</code> toe te voegen aan de figuur onder <code>labs()</code> (regel 9).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>dutch_means <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  <span class="fu">filter</span>(skill <span class="sc">==</span> <span class="st">"production"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb50-3"><a href="#cb50-3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> mean_number_words )) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> wordbank_dutch_child, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> production), <span class="at">color =</span> <span class="st">"grey80"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"deepskyblue4"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"mean number of words"</span>,</span>
<span id="cb50-7"><a href="#cb50-7"></a>       <span class="at">x =</span> <span class="st">"age in months"</span>,</span>
<span id="cb50-8"><a href="#cb50-8"></a>       <span class="at">title =</span> <span class="st">"Word production by age"</span>,</span>
<span id="cb50-9"><a href="#cb50-9"></a>       <span class="at">caption =</span> <span class="st">"large circles show mean per age group</span><span class="sc">\n</span><span class="st">small circles show scores of individual children"</span>) <span class="sc">+</span></span>
<span id="cb50-10"><a href="#cb50-10"></a>  <span class="fu">theme_minimal</span>(<span class="dv">14</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="numeriek_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Wat valt op? We zien dat er veel variatie in aantal kinderen per leeftijd zit en dat er veel variatie in de spreiding om het gemiddelde per leeftijd zit. Bij de leeftijd van 23 is deze spreiding bijvoorbeeld enorm en bij 19 maanden heel beperkt, terwijl bij 26 maanden de individuele observaties erg ver van het gemiddelde afliggen. Het toevoegen van de individuele datapunten maakt meteen duidelijk dat het gemiddelde niet altijd een goede weergave van de onderliggende data is. Je zou nu zelf een vergelijkbare grafiek kunnen maken voor woordbegrip.</p>
</section>
<section id="verder-leren" class="level2 unnumbered page-columns page-full">
<h2 class="unnumbered anchored" data-anchor-id="verder-leren">Verder leren</h2>
<ul>
<li>Lees <a href="https://socviz.co/groupfacettx.html#histograms">sectie 4.6</a> en <a href="https://socviz.co/workgeoms.html#continuous-variables-by-group-or-category">sectie 5.2</a> van <span class="citation" data-cites="IntroDataVis">Healy (<a href="index.html#ref-IntroDataVis" role="doc-biblioref">2019</a>)</span> voor meer inzicht in het visualiseren van numerieke variabelen.</li>
<li><a href="https://r4ds.hadley.nz/data-tidy.html">Hoofdstuk 5</a> van <span class="citation" data-cites="R4DS">Wickham et al. (<a href="index.html#ref-R4DS" role="doc-biblioref">2023</a>)</span> geeft meer informatie over het omzetten van datatabellen van en naar <em>long/wide</em> formaat.</li>
<li>Het <a href="https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf">ggplot2 cheat sheet</a> zou inmiddels minder geheimen voor je moeten hebben en geeft een goed overzicht van wat er tot nu besproken is.</li>
</ul>
<div class="no-row-height column-margin column-container"><div id="ref-IntroDataVis" class="csl-entry" role="listitem">
Healy, K. (2019). <em>Data Visualisation: A Practical Introduction.</em> Princeton University Press. <a href="https://socviz.co/">https://socviz.co/</a>
</div><div id="ref-R4DS" class="csl-entry" role="listitem">
Wickham, H., Çetinkaya-Rundel, M., &amp; Grolemund, G. (2023). <em><span>R</span> for Data Science</em> (2de dr.). O’Reilly. <a href="https://r4ds.hadley.nz/">https://r4ds.hadley.nz/</a>
</div></div><p>Nu zou je in staat moeten zijn Practicum 5 te maken.</p>



</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./factoren.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorische variabelen</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./practica.html" class="pagination-link">
        <span class="nav-page-text">Practica</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>